### ISSUE TITLE
Deidentification and Encryption descriptions swapped in ES, FR, AR, unsure of UA, RU

### ISSUE THREAD

**Issue by cheyennelauclair** [mercycorps/DPP-guides#12]
The Deidentification and Encryption descriptions in the DPP Guide PDF Table of Contents as well as the top level READMEs are swapped. EN README is accurate and I am correcting AR now. @Shadrock We need to review and correct ES, FR, UA, and RU localizations.
![Capture](https://user-images.githubusercontent.com/107952902/176268252-35f889c1-e491-4cb9-a7fb-d0cee9a49e63.PNG)

**Comment by Shadrock** [comment]
Great @cheyennelauclair , thanks for logging the issue!

**Comment by Shadrock** [comment]
Pushed fixes for FR and EN. Hope to push RU and UA today, too.

**Comment by Shadrock** [comment]
Pushed fix for RU + UA as well, closing this out!
